added attribution, MAX_RAM and OPTIONS variables, is_running function (used extensively throughout script)

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -1,5 +1,6 @@
 #!/bin/bash
 # /etc/init.d/minecraft
+# version 1.2.0 2012-06-11 (YYYY-MM-DD)
 
 ### BEGIN INIT INFO
 # Provides:   minecraft
@@ -14,6 +15,7 @@
 ### END INIT INFO
 
 ### Based on http://www.minecraftwiki.net/wiki/Server_startup_script
+### Forked from https://www.github.com/karrth/minecraft-init
 
 
 # Name of server.jar file
@@ -23,10 +25,9 @@ USERNAME="minecraft"
 # Path to minecraft directory
 MCPATH="/home/${USERNAME}/server"
 CPU_COUNT=2
-# Change the values of -Xmx###M and -Xms###M to how much ram you want to give to the
-# server. Remember to give the ramdisk enough space. Subtract from the total amount
-# of RAM available the size of your map and the RAM-consumption of your base system.
-INVOCATION="java -Xmx1536M -Xincgc -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE nogui"
+MAX_RAM="1536M"
+OPTIONS="nogui"
+INVOCATION="java -Xmx${MAX_RAM} -Xincgc -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE $OPTIONS"
 # Where the world backups should go
 BACKUPPATH="/home/${USERNAME}/backups/world"
 # Where the logs are copied when running log-roll
@@ -47,33 +48,61 @@ as_user() {
 		su - $USERNAME -c "$1"
 	fi
 }
+is_running() {
+	# Checks for the minecraft server's screen session
+	# returns true if it exists
+	#if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if pgrep -u $USERNAME -f $SERVICE > /dev/null
+	then
+		return 0
+	fi
+	return 1
+}
 datepath() {
 	echo $1`date +%FT%T`$3
 }
 mc_start() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 	then
 		echo "Tried to start but $SERVICE was already running!"
 	else
 		echo "$SERVICE was not running... starting."
 		cd $MCPATH
-		as_user "cd $MCPATH && screen -dmS minecraft $INVOCATION"
-		sleep 7
-		if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
-		then
-			echo "$SERVICE is now running."
-		else
-			echo "Could not start $SERVICE."
-		fi
+		as_user "cd $MCPATH && screen -dmS $USERNAME $INVOCATION"
+
+		#sleep 7
+		#if is_running
+		#then
+		#	echo "$SERVICE is now running."
+		#else
+		#	echo "Could not start $SERVICE."
+		#fi
+
+		# Waiting for server to start
+		seconds=0
+		until is_running
+		do
+			sleep 1
+			seconds=$seconds+1
+			# If startup takes longer than 30 seconds, abort
+			if [[ $seconds -ge 30 ]]
+			then
+				echo "$SERVICE failed to start. Aborting."
+				exit 1
+			fi
+			# Show that script is thinking
+			echo "..."
+		done
+		echo "$SERVICE is now running."
 	fi
 }
 
 mc_saveoff() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 	then
 		echo "$SERVICE is running... suspending saves"
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"save-off\"\015'"
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"save-all\"\015'"
+		as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"save-off\"\015'"
+		as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"save-all\"\015'"
 		sync
 		sleep 10
 	else
@@ -82,37 +111,67 @@ mc_saveoff() {
 }
 
 mc_saveon() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 	then
 		echo "$SERVICE is running... re-enabling saves"
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"save-on\"\015'"
+		as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"save-on\"\015'"
 	else
 		echo "$SERVICE was not running. Not resuming saves."
 	fi
 }
 
 mc_stop() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 	then
 		echo "$SERVICE is running... stopping."
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"save-all\"\015'"
+		echo "Saving worlds..."
+		as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"save-all\"\015'"
 		sleep 10
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"stop\"\015'"
-		sleep 7
+		echo "Stopping server..."
+		as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"stop\"\015'"
+		sleep 0.5
+		# Waiting for server to shut down
+		seconds=0
+		while is_running
+		do
+			sleep 1
+			seconds=$seconds+1
+			# If shutdown takes longer than 30 seconds, abort
+			if [[ $seconds -ge 30 ]]
+			then
+				logger -t minecraft "$SERVICE failed to halt."
+				echo "$SERVICE failed to halt. Aborting."
+				exit 1
+			fi
+			echo "..."
+		done
+		echo "$SERVICE is shut down."
 	else
 		echo "$SERVICE was not running."
 	fi
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
-	then
-		echo "$SERVICE could not be shut down... still running."
-	else
-		echo "$SERVICE is shut down."
-	fi
+
+	#if is_running
+	#then
+	#	echo "$SERVICE could not be shut down... still running."
+	#else
+	#	echo "$SERVICE is shut down."
+	#fi
 }
 mc_log_roll() {
+	if [ ! -d $LOGPATH ]; then
+		as_user "mkdir -p $LOGPATH"
+	fi
         echo "Rolling minecraft server logs"
 	path=`datepath $LOGPATH/server_ .log.gz .log`
-	as_user "mv $MCPATH/server.log $path && gzip $path"
+	as_user "cp $MCPATH/server.log $path && gzip $path"
+	# if server.log copy was successful
+	if [ $? -eq 0 ]; then
+		# Delete log file and create new one
+		as_user "cp /dev/null $MCPATH/server.log"
+		as_user "echo \"Previous log rolled to $path\" > $MCPATH/server.log "
+	else
+		echo "Failed to roll log to $LOGPATH/server_$path.log.gz"
+	fi
 }
 mc_whole_backup() {
         echo "Backing up minecraft server folder"
@@ -135,8 +194,22 @@ mc_world_backup() {
 	path=`datepath $BACKUPPATH/$TODAY/world_the_end_ .tar.bz2 .tar.bz2`
 	as_user "tar -hcjf $path $MCPATH/world_the_end"
 }
+mc_command() {
+	command="$1";
+	if is_running
+	then
+		pre_log_len=`wc -l "$MCPATH/server.log" | awk '{print $1}'`
+		echo "$SERVICE is running... executing command"
+		as_user "screen -p 0 -S minecraft -X eval 'stuff \"$command\"\015'"
+		sleep .1 # assumes that the command will run and print to the log file in less than .1 seconds
+		# print output
+		tail -n $[`wc -l "$MCPATH/server.log" | awk '{print $1}'`-$pre_log_len] "$MCPATH/server.log"
+	else
+		echo "$SERVICE is not running. Cannot execute command."
+	fi
+}
 to_ram() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 	then
 		echo "Cannot copy to ram, $SERVICE is currently running!"
 	else
@@ -192,12 +265,12 @@ to_disk() {
 }
 
 mc_update() {
-	if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
+	if is_running
 		then
 			echo "$SERVICE is running! Will not start update."
 	else
 		### update minecraft_server.jar
-		echo "Updating minecraft_server.jar...."
+		echo "Updating minecraft_server.jar..."
 		MC_SERVER_URL=http://minecraft.net/`wget -q -O - http://www.minecraft.net/download.jsp | grep minecraft_server.jar\</a\> | cut -d \" -f 2`
 		as_user "cd $MCPATH && wget -q -O $MCPATH/minecraft_server.jar.update $MC_SERVER_URL"
 		if [ -f $MCPATH/minecraft_server.jar.update ]
@@ -215,7 +288,6 @@ mc_update() {
 		fi
 
 		### update craftbukkit
-
 		echo "Updating craftbukkit...."
 		as_user "cd $MCPATH && wget -q -O $MCPATH/craftbukkit.jar.update http://dl.bukkit.org/latest-rb/craftbukkit.jar"
 		if [ -f $MCPATH/craftbukkit.jar.update ]
@@ -238,24 +310,36 @@ mc_update() {
 case "$1" in
 	start)
 		# Starts the server
-		to_ram
-		mc_start
+		if is_running; then
+			echo "$SERVICE already running."
+		else
+			to_ram
+			mc_start
+		fi
 		;;
 	stop)
 		# Stops the server
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"say SERVER SHUTTING DOWN!\"\015'"
-		mc_stop
-		to_disk
+		if is_running; then
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say SERVER SHUTTING DOWN!\"\015'"
+			mc_stop
+			to_disk
+		else
+			echo "$SERVICE not running."
+		fi
 		;;
 	restart)
 		# Restarts the server
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"say SERVER REBOOT IN 10 SECONDS.\"\015'"
-		mc_stop
-		mc_start
+		if is_running; then
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say SERVER REBOOT IN 10 SECONDS.\"\015'"
+			mc_stop
+			mc_start
+		else
+			echo "$SERVICE not running. Cannot restart."
+		fi
 		;;
         update)
                 #update minecraft_server.jar and craftbukkit.jar
-                as_user "screen -p 0 -S minecraft -X eval 'stuff \"say SERVER REBOOT/UPDATE IN 10 SECONDS.\"\015'"
+                as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say SERVER REBOOT/UPDATE IN 10 SECONDS.\"\015'"
                 mc_stop
 		to_disk
                 mc_whole_backup
@@ -264,51 +348,91 @@ case "$1" in
                 ;;
 	backup)
 		# Backup world
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"say Backing up world.\"\015'"
-		mc_saveoff
-		to_disk
-		mc_world_backup
-		mc_saveon
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"say Backup complete.\"\015'"
+		if is_running; then
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say Backing up world.\"\015'"
+			mc_saveoff
+			to_disk
+			mc_world_backup
+			mc_saveon
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say Backup complete.\"\015'"
+		else
+			mc_world_backup
+		fi
 		;;
 	whole-backup)
 		# Backup everything
-		mc_saveoff
-		to_disk
-		mc_whole_backup
-		mc_saveon
+		if is_running; then
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff \"say COMPLETE SERVER BACKUP COMMENCING. REBOOT IN 10 SECONDS.\"\015'"
+			#mc_saveoff
+			mc_stop
+			to_disk
+			mc_whole_backup
+			#mc_saveon
+			mc_start
+		else
+			mc_whole_backup
+		fi
 		;;
 	to-disk)
-		# Writes from the ramdisk to disk, in case the server crashes. 
-		# Using ramdisk speeds things up a lot, especially if you allow
-		# teleportation on the server.
+		# Writes from the ramdisk to disk, in case the server crashes.
 		mc_saveoff
 		to_disk
 		mc_saveon
 		;;
 	connected)
 		# Lists connected users
-		as_user "screen -p 0 -S minecraft -X eval 'stuff list\015'"
-		sleep 3s
-		tac $MCPATH/server.log | grep -m 1 "Connected"
+		if is_running; then
+			as_user "screen -p 0 -S $USERNAME -X eval 'stuff list\015'"
+			sleep 3s
+			tac $MCPATH/server.log | grep -m 1 "Connected"
+		else
+			echo "$SERVICE not running."
+		fi
 		;;
 	last)
 		# greps for recently logged in users
 		echo Recently logged in users:
 		cat $MCPATH/server.log | awk '/entity|conn/ {sub(/lost/,"disconnected");print $1,$2,$4,$5}'
 		;;
+	console)
+		# shows server console with screen
+		echo "Press 'Ctrl+A' and then press 'D' to exit the console."
+		echo "Hit any key to continue:"
+		read
+		clear
+		as_user "screen -r"
+		;;
+	say)
+		# executes say command on the server console
+		if [ $* -gt 1 ]; then
+			shift
+			mc_command "say $*"
+		else
+			echo "What do you want to say?"
+		fi
+		;;
+	command)
+		# executes a command on the server console
+		if [ $# -gt 1 ]; then
+			shift
+			mc_command "$*"
+		else
+			echo "Must specify server command (try 'help'?)"
+		fi
+		;;
 	log-roll)
 		# Moves and Gzips the logfile, a big log file slows down the
 		# server A LOT (what was notch thinking?)
-		as_user "screen -p 0 -S minecraft -X eval 'stuff \"say ROUTINE REBOOT IN 10 SECONDS. BACK IN 30 SECONDS.\"\015'"
-		mc_stop
+		#as_user "screen -p 0 -S minecraft -X eval 'stuff \"say ROUTINE REBOOT IN 10 SECONDS. BACK IN 30 SECONDS.\"\015'"
+		#mc_stop
+		#sleep 20s
 		mc_log_roll
-		mc_start
+		#sleep 10s
+		#mc_start
 		;;
 	status)
 		# Shows server status
-		if ps ax | grep -v grep | grep -v -i SCREEN | grep $SERVICE > /dev/null
-		then
+		if is_running; then
 			echo "$SERVICE is running."
 		else
 			echo "$SERVICE is not running."
@@ -318,7 +442,7 @@ case "$1" in
 		echo Craftbukkit version `awk '/Craftbukkit/ {sub(/\)/, ""); print $12}' $MCPATH/server.log`
         	;;
 	*)
-		echo "Usage: /etc/init.d/minecraft {start|stop|backup|whole-backup|update|log-roll|to-disk|connected|last|status|restart|version}"
+		echo "Usage: /etc/init.d/minecraft {start|stop|restart|backup|whole-backup|update|to-disk|connected|last|console|say|command|log-roll|status|version}"
 		exit 1
 		;;
 esac
